name: SCA Check
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  sca-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Build with Ant
        run: ant build  # Adjust to your actual build command
      
      - name: Create project zip
        run: zip -r project.zip . -x "*.git*" "*/node_modules/*" "*/vendor/*" "*.zip"
      
      - name: Perform SCA Scan
        id: sca
        run: |
          RESPONSE=$(curl -X POST             -H "Client-ID: ${{ secrets.INTRUCEPT_CLIENT_ID }}"             -H "Client-Secret: ${{ secrets.INTRUCEPT_CLIENT_SECRET }}"             -F "projectZipFile=@project.zip"             -F "applicationId=${{ secrets.INTRUCEPT_APPLICATION_ID }}"             -F "scanName=Python SCA Scan - ${{ github.sha }}"             -F "language=python"             https://appsecops-api.intruceptlabs.com/api/v1/integrations/sca-scans)          
          
            # Check for error in response
            ERROR=$(echo "$RESPONSE" | jq -r '.error // empty')
            if [ ! -z "$ERROR" ]; then
              echo "Error: $ERROR"
              exit 1
            else
              VULNS_TABLE=$(echo "$RESPONSE" | jq -r '.vulnsTable')
              echo "Vulnerabilities Table:"
              echo "$VULNS_TABLE"
            fi
